version: '3.8'

services:
  podium:
    container_name: podium
    build: .
    # ports:
      # - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./settings.toml:/app/app/settings.toml
      - ./.secrets.toml:/app/app/.secrets.toml